.TH QUADRO 1 "2022 November" "Screenshot Utility Commands"
.SH NAME
quadro - take screenshots
.SH SYNOPSIS
.B quadro
[\fIOPTION\fR]...
.SH DESCRIPTION
.PP
Take a screenshot considering OPTIONs passed from the command-line and save it to a file.
.TP
\fB\-f\fR \fIFILENAME\fR
save screenshot with filename
.TP
\fB\-g\fR \fIGEOMETRY\fR
screenshot region defined by geometry; e.g. '-g 496x397+917+158'; see XParseGeometry(3)
.SH AUTHOR
Written by \fIhttps://github.com/thalting\fR.

Man page written by \fIhttps://github.com/victorcebarros\fR.
.SH REPORTING BUGS
Quadro Official Repository: <https://github.com/thalting/quadro/>
.SH COPYRIGHT
Licensed under The Unlicense. Refer to LICENSE for more information.
.SH SEE ALSO
\fBslop\fP(1)
\fBhacksaw\fP(1)
